# Generated by Django 4.2.4 on 2023-09-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_birthdate_user_currency_user_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='superhost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('bn', 'Bangla'), ('sp', 'Spanish')], max_length=2, null=True),
        ),
    ]
